version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-container
    ports:
      - "8081:8081"
    networks:
      - app-network
    env_file:
      - ./backend/.env
    restart: unless-stopped

  db:
    image: dbeaver/cloudbeaver
    container_name: cloudbeaver-container
    ports:
      - "8082:8978"
    networks:
      - app-network
    env_file:
      - ./database/.env
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/data
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  cloudbeaver_data:
    driver: local
