version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-container
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - APP_ENV=production

  db:
    image: dbeaver/cloudbeaver
    container_name: cloudbeaver-container
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - CB_SECURITY_ENABLED=true
      - CB_USER=admin
      - CB_PASSWORD=examplepw
      - CB_DATASOURCE_NAME=PostgreSQL-DB
      - CB_DATASOURCE_URL=jdbc:postgresql://192.168.8.30:5432
      - CB_DATASOURCE_USER=postgres
      - CB_DATASOURCE_PASSWORD=examplepw
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
